/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/stage-final.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Stage(props) {
    const { nodes, materials } = useGLTF("models/stage-final.glb");
    return (
        <group {...props} dispose={null}>
            <group scale={0.001}>
                <group rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
                    <group
                        position={[9109.701, -8105.565, 5964.958]}
                        rotation={[0, 0, -Math.PI / 2]}
                    >
                        <group
                            position={[-5.016, -268.124, 3775.374]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4570_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4570_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[0.001, 0, -0.001]}
                            />
                        </group>
                        <group
                            position={[-5.016, -268.124, 2503.792]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4571_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4571_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[0.001, 0, -0.001]}
                            />
                        </group>
                        <group
                            position={[-5.016, -268.124, 1232.209]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4572_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4572_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[0.001, 0, -0.001]}
                            />
                        </group>
                        <group
                            position={[-5.016, -268.124, -39.373]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4573_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4573_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[0.001, 0, -0.001]}
                            />
                        </group>
                        <group
                            position={[-5.016, -268.124, -1310.955]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4574_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4574_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[0.001, 0, -0.001]}
                            />
                        </group>
                        <group
                            position={[-5.016, -268.124, -2582.537]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4575_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4575_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[0.001, 0, -0.001]}
                            />
                        </group>
                        <group
                            position={[-5.016, -268.124, -3854.119]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4576_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4576_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[0.001, 0, -0.001]}
                            />
                        </group>
                        <mesh
                            geometry={
                                nodes["Rectangle2106822741_21_-_Default_0"]
                                    .geometry
                            }
                            material={materials["21_-_Default"]}
                            position={[0, 48.125, -4210.5]}
                        />
                    </group>
                    <group
                        position={[8348.857, -14612.939, 5964.958]}
                        rotation={[0, 0, -Math.PI / 2]}
                    >
                        <group
                            position={[-5.015, -268.125, 3775.374]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4577_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4577_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[0.001, 0, -0.001]}
                            />
                        </group>
                        <group
                            position={[-5.015, -268.125, 2503.792]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4578_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4578_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[0.001, 0, -0.001]}
                            />
                        </group>
                        <group
                            position={[-5.015, -268.125, 1232.209]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4579_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4579_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[0.001, 0, -0.001]}
                            />
                        </group>
                        <group
                            position={[-5.015, -268.125, -39.373]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4580_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4580_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[0.001, 0, -0.001]}
                            />
                        </group>
                        <group
                            position={[-5.015, -268.125, -1310.955]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4581_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[0.001, 0, 0]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4581_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[0.001, 0, 0]}
                            />
                        </group>
                        <group
                            position={[-5.015, -268.125, -2582.537]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4582_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4582_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[0.001, 0, -0.001]}
                            />
                        </group>
                        <group
                            position={[-5.015, -268.125, -3854.119]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4583_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4583_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[0.001, 0, -0.001]}
                            />
                        </group>
                        <group position={[0.001, 48.126, -4210.5]}>
                            <mesh
                                geometry={
                                    nodes["Rectangle2106822742_21_-_Default_0"]
                                        .geometry
                                }
                                material={materials["21_-_Default"]}
                                position={[0.001, 0, 0]}
                            />
                        </group>
                    </group>
                    <group
                        position={[8348.857, 14578.81, 5964.958]}
                        rotation={[0, 0, -Math.PI / 2]}
                    >
                        <group
                            position={[-5.017, -268.125, 3775.374]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4584_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[-0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4584_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[-0.001, 0, -0.001]}
                            />
                        </group>
                        <group
                            position={[-5.017, -268.125, 2503.792]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4585_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[-0.001, 0, 0]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4585_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[-0.001, 0, 0]}
                            />
                        </group>
                        <group
                            position={[-5.017, -268.125, 1232.209]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4586_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[-0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4586_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[-0.001, 0, -0.001]}
                            />
                        </group>
                        <group
                            position={[-5.017, -268.125, -39.373]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4587_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[-0.001, 0, 0]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4587_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[-0.001, 0, 0]}
                            />
                        </group>
                        <group
                            position={[-5.017, -268.125, -1310.955]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4588_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[-0.001, 0, 0]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4588_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[-0.001, 0, 0]}
                            />
                        </group>
                        <group
                            position={[-5.017, -268.125, -2582.537]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4589_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[-0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4589_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[-0.001, 0, -0.001]}
                            />
                        </group>
                        <group
                            position={[-5.017, -268.125, -3854.119]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4590_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[-0.001, 0, 0]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4590_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[-0.001, 0, 0]}
                            />
                        </group>
                        <mesh
                            geometry={
                                nodes["Rectangle2106822743_21_-_Default_0"]
                                    .geometry
                            }
                            material={materials["21_-_Default"]}
                            position={[0, 48.126, -4210.5]}
                        />
                    </group>
                    <group
                        position={[9109.701, 8071.435, 5964.958]}
                        rotation={[0, 0, -Math.PI / 2]}
                    >
                        <group
                            position={[-5.016, -268.124, 3775.374]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4591_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[-0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4591_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[-0.001, 0, -0.001]}
                            />
                        </group>
                        <group
                            position={[-5.016, -268.124, 2503.792]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4592_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[-0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4592_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[-0.001, 0, -0.001]}
                            />
                        </group>
                        <group
                            position={[-5.016, -268.124, 1232.209]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4593_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[-0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4593_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[-0.001, 0, -0.001]}
                            />
                        </group>
                        <group
                            position={[-5.016, -268.124, -39.373]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4594_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[-0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4594_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[-0.001, 0, -0.001]}
                            />
                        </group>
                        <group
                            position={[-5.016, -268.124, -1310.955]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4595_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[-0.001, 0, 0]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4595_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[-0.001, 0, 0]}
                            />
                        </group>
                        <group
                            position={[-5.016, -268.124, -2582.537]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4596_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[-0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4596_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[-0.001, 0, -0.001]}
                            />
                        </group>
                        <group
                            position={[-5.016, -268.124, -3854.119]}
                            rotation={[Math.PI / 2, 0, 0]}
                        >
                            <mesh
                                geometry={
                                    nodes[
                                        "Circle4597_01_-_Dsddaefaudsdadltdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsddaefaudsdadltdas36"]
                                }
                                position={[-0.001, 0, -0.001]}
                            />
                            <mesh
                                geometry={
                                    nodes["Circle4597_20_-_Default_0"].geometry
                                }
                                material={materials["20_-_Default"]}
                                position={[-0.001, 0, -0.001]}
                            />
                        </group>
                        <mesh
                            geometry={
                                nodes["Rectangle2106822744_21_-_Default_0"]
                                    .geometry
                            }
                            material={materials["21_-_Default"]}
                            position={[0, 48.125, -4210.5]}
                        />
                    </group>
                    <group
                        position={[1167.732, -11475.565, -3.967]}
                        rotation={[0, 0, -Math.PI / 2]}
                    >
                        <group
                            position={[3109.105, 107.687, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape29_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[279.015, 1980.397, 0]}
                            />
                        </group>
                        <group
                            position={[513.992, -64.25, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape30_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[311.208, 1982.526, 0]}
                            />
                        </group>
                        <group
                            position={[783.703, 2041.719, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape31_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[307.862, 1956.401, 0]}
                            />
                        </group>
                        <group
                            position={[-422.567, 2265.984, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape32_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[322.825, 1953.623, 0]}
                            />
                        </group>
                        <group
                            position={[-359.271, -505.094, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape33_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[322.04, 1987.997, 0]}
                            />
                        </group>
                        <group
                            position={[2074.754, 29.625, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape34_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[291.846, 1981.367, 0]}
                            />
                        </group>
                        <group
                            position={[-2024.094, 0.016, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape35_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[342.693, 1981.735, 0]}
                            />
                        </group>
                    </group>
                    <group
                        position={[-3094.018, -4422.69, -3.967]}
                        rotation={[0, 0, -Math.PI / 2]}
                    >
                        <group
                            position={[3109.105, 107.687, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape946_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[279.015, 1980.397, 0]}
                            />
                        </group>
                        <group
                            position={[513.992, -64.25, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape947_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[311.208, 1982.526, 0]}
                            />
                        </group>
                        <group
                            position={[783.703, 2041.719, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape948_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[307.862, 1956.401, 0]}
                            />
                        </group>
                        <group
                            position={[-422.567, 2265.984, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape949_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[322.825, 1953.623, 0]}
                            />
                        </group>
                        <group
                            position={[-359.272, -505.094, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape950_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[322.04, 1987.997, 0]}
                            />
                        </group>
                        <group
                            position={[2074.753, 29.625, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape951_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[291.846, 1981.367, 0]}
                            />
                        </group>
                        <group
                            position={[-2024.094, 0.015, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape952_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[342.693, 1981.735, 0]}
                            />
                        </group>
                    </group>
                    <group
                        position={[-2887.393, 4589.935, -3.967]}
                        rotation={[Math.PI, 0, Math.PI / 2]}
                        scale={-1}
                    >
                        <group
                            position={[3109.106, 107.687, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape953_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[279.015, 1980.397, 0]}
                            />
                        </group>
                        <group
                            position={[513.992, -64.25, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape954_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[311.208, 1982.526, 0]}
                            />
                        </group>
                        <group
                            position={[783.704, 2041.719, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape955_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[307.862, 1956.401, 0]}
                            />
                        </group>
                        <group
                            position={[-422.567, 2265.984, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape956_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[322.825, 1953.623, 0]}
                            />
                        </group>
                        <group
                            position={[-359.272, -505.094, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape957_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[322.04, 1987.997, 0]}
                            />
                        </group>
                        <group
                            position={[2074.754, 29.625, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape958_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[291.846, 1981.367, 0]}
                            />
                        </group>
                        <group
                            position={[-2024.094, 0.016, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape959_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[342.693, 1981.735, 0]}
                            />
                        </group>
                    </group>
                    <group
                        position={[1257.857, 11428.06, -3.967]}
                        rotation={[Math.PI, 0, Math.PI / 2]}
                        scale={-1}
                    >
                        <group
                            position={[3109.106, 107.688, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape960_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[279.015, 1980.397, 0]}
                            />
                        </group>
                        <group
                            position={[513.992, -64.25, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape961_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[311.208, 1982.526, 0]}
                            />
                        </group>
                        <group
                            position={[783.703, 2041.719, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape962_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[307.862, 1956.401, 0]}
                            />
                        </group>
                        <group
                            position={[-422.566, 2265.985, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape963_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[322.825, 1953.623, 0]}
                            />
                        </group>
                        <group
                            position={[-359.271, -505.094, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape964_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[322.04, 1987.997, 0]}
                            />
                        </group>
                        <group
                            position={[2074.754, 29.625, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape965_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[291.846, 1981.367, 0]}
                            />
                        </group>
                        <group
                            position={[-2024.094, 0.016, -40.306]}
                            scale={80.612}
                        >
                            <mesh
                                geometry={
                                    nodes["Shape966_01_-_Defaultdas36_0"]
                                        .geometry
                                }
                                material={materials["01_-_Defaultdas36"]}
                                position={[342.693, 1981.735, 0]}
                            />
                        </group>
                    </group>
                    <group
                        position={[4777.576, -15396.69, 11132.598]}
                        rotation={[Math.PI, 0, Math.PI / 2]}
                        scale={-1}
                    >
                        <mesh
                            geometry={
                                nodes[
                                    "Line2062814742_01_-_Defadasult21022240_0"
                                ].geometry
                            }
                            material={materials["01_-_Defadasult210.2.2240"]}
                            position={[0, 0, 0.001]}
                        />
                    </group>
                    <group
                        position={[4777.576, -15396.69, 12088.867]}
                        rotation={[Math.PI, 0, Math.PI / 2]}
                        scale={-1}
                    >
                        <mesh
                            geometry={
                                nodes[
                                    "Line2062814743_01_-_Defadasult21022240_0"
                                ].geometry
                            }
                            material={materials["01_-_Defadasult210.2.2240"]}
                            position={[0, 0.001, 0]}
                        />
                    </group>
                    <group
                        position={[4777.576, -15396.69, 13045.14]}
                        rotation={[Math.PI, 0, Math.PI / 2]}
                        scale={-1}
                    >
                        <mesh
                            geometry={
                                nodes[
                                    "Line2062814744_01_-_Defadasult21022240_0"
                                ].geometry
                            }
                            material={materials["01_-_Defadasult210.2.2240"]}
                            position={[0, 0.001, 0]}
                        />
                    </group>
                    <group
                        position={[-8435.579, 8.06, 1865.075]}
                        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                        scale={[143.652, 143.652, 18.818]}
                    >
                        <mesh
                            geometry={
                                nodes["Object664_01_-_Dsdsaddaefaultdas36_0"]
                                    .geometry
                            }
                            material={materials["01_-_Dsdsaddaefaultdas36"]}
                            position={[278.206, 557.407, 13.292]}
                        />
                    </group>
                    <group
                        position={[4280.919, -20227.191, 3386.181]}
                        rotation={[0, 0, -Math.PI / 2]}
                    >
                        <mesh
                            geometry={
                                nodes["Rectangle140_20_-_Defaultdsaas_0"]
                                    .geometry
                            }
                            material={materials["20_-_Defaultdsaas"]}
                            position={[-0.001, 0.001, 0]}
                        />
                        <mesh
                            geometry={
                                nodes["Rectangle140_21_-_Defaultsadsasadd_0"]
                                    .geometry
                            }
                            material={materials["21_-_Defaultsadsasadd"]}
                            position={[-0.001, 0.001, 0]}
                        />
                        <mesh
                            geometry={
                                nodes["Rectangle140_21_-_Defaultsasadd_0"]
                                    .geometry
                            }
                            material={materials["21_-_Defaultsasadd"]}
                            position={[-0.001, 0.001, 0]}
                        />
                    </group>
                    <group
                        position={[1748.107, -22.815, 14.124]}
                        rotation={[0, 0, -Math.PI / 4]}
                    >
                        <mesh
                            geometry={
                                nodes[
                                    "Rectangle146_01_-_Dsdsaddaefdsaaultdas36_0"
                                ].geometry
                            }
                            material={
                                materials["01_-_Dsdsaddaefdsaaultdas36_0"]
                            }
                        />
                        <mesh
                            geometry={
                                nodes["Rectangle146_20_-_Default_0"].geometry
                            }
                            material={materials["20_-_Default"]}
                        />
                        <mesh
                            geometry={
                                nodes["Rectangle146_21_-_Defauldsaastsad_0"]
                                    .geometry
                            }
                            material={materials["21_-_Defauldsaastsad"]}
                        />
                    </group>
                    <group
                        position={[5158.451, -104.19, 11982.257]}
                        rotation={[0, 0, -Math.PI / 4]}
                    >
                        <group position={[-2672.912, -802.651, -999.999]}>
                            <mesh
                                geometry={
                                    nodes[
                                        "Rectangle147_01_-_Dsdsaddaefdsaaultdas36_0"
                                    ].geometry
                                }
                                material={
                                    materials["01_-_Dsdsaddaefdsaaultdas36"]
                                }
                            />
                            <mesh
                                geometry={
                                    nodes["Rectangle147_20_-_Defaultdsaas_0"]
                                        .geometry
                                }
                                material={materials["20_-_Defaultdsaas_0"]}
                            />
                        </group>
                    </group>
                    <group
                        position={[5158.451, -104.19, 10773.789]}
                        rotation={[0, 0, -Math.PI / 4]}
                    >
                        <group position={[-2672.912, -802.651, -81.185]}>
                            <mesh
                                geometry={
                                    nodes[
                                        "Rectangle2106822820_21_-_Defaultsad_0"
                                    ].geometry
                                }
                                material={materials["21_-_Defaultsad"]}
                                position={[0, 0, -0.001]}
                            />
                        </group>
                    </group>
                    <group
                        position={[5158.451, -104.19, 13169.543]}
                        rotation={[0, 0, -Math.PI / 4]}
                    >
                        <group position={[-2672.911, -802.651, -81.184]}>
                            <mesh
                                geometry={
                                    nodes["Rectangle419_21_-_Defaultsad_0"]
                                        .geometry
                                }
                                material={materials["21_-_Defaultsad"]}
                                position={[0, 0, -0.001]}
                            />
                        </group>
                    </group>
                    <mesh
                        geometry={
                            nodes["Rectangle2106822737_20_-_Default_0"].geometry
                        }
                        material={materials["20_-_Default"]}
                        position={[-7698.455, -36.94, 14.124]}
                        rotation={[0, 0, -Math.PI / 4]}
                    />
                    <mesh
                        geometry={
                            nodes[
                                "Rectangle2106822738_01_-_Defadasult21022240_0"
                            ].geometry
                        }
                        material={materials["01_-_Defadasult210.2.2240"]}
                        position={[-7698.455, -36.94, 14.124]}
                        rotation={[0, 0, -Math.PI / 4]}
                    />
                    <mesh
                        geometry={
                            nodes["Rectangle418_21_-_Defaultsad_0"].geometry
                        }
                        material={materials["21_-_Defaultsad"]}
                        position={[1748.107, -22.815, 14.124]}
                        rotation={[0, 0, -Math.PI / 4]}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/stage-final.glb");
